### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by chdorb** [shimt/pam-exec-oauth2#1]
When building pam-exec-oauth2 this error appears:
`./main.go:110: oauth2Config.PasswordCredentialsTokenEx undefined (type oauth2.Config has no field or method PasswordCredentialsTokenEx)`

**Comment by shimt** [comment]
Are you compiling under $GOPATH?

# ex1 (OK)
% echo $GOPATH
~/go
% pwd
~/go/src/github.com/shimt/pam-exec-oauth2
% go build

# ex2 (NG)
% echo $GOPATH
~/go
% pwd
~/tmp/pam-exec-oauth2
% go build
# ~/tmp/pam-exec-oauth2
./main.go:110:34: oauth2Config.PasswordCredentialsTokenEx undefined (type oauth2.Config has no field or method PasswordCredentialsTokenEx)

**Comment by chdorb** [comment]
It's OK. Thank you ! and sorry…

[~]$ mkdir go
[~]$ export GOPATH=~/go                                                                                
[~]$ cd $GOPATH                                                                                        
[~/go]$ pwd                                                                                            
/home/chdorb/go
[~/go]$ go get github.com/shimt/pam-exec-oauth2
[~/go]$ cd src/github.com/shimt/pam-exec-oauth2                                                        
[~/go/src/github.com/shimt/pam-exec-oauth2]$ go build
[~/go/src/github.com/shimt/pam-exec-oauth2]$ ls -l
total 9240
-rw-r--r-- 1 chdorb chdorb      78 15 oct.  10:45 build-linux-amd64.bat
-rw-r--r-- 1 chdorb chdorb      78 15 oct.  10:45 build-linux-arm64.bat
-rw-r--r-- 1 chdorb chdorb      76 15 oct.  10:45 build-linux-arm.bat
-rw-r--r-- 1 chdorb chdorb    1072 15 oct.  10:45 LICENSE
-rw-r--r-- 1 chdorb chdorb    3830 15 oct.  10:45 main.go
-rwxr-xr-x 1 chdorb chdorb 9431240 15 oct.  10:46 pam-exec-oauth2
-rw-r--r-- 1 chdorb chdorb    1080 15 oct.  10:45 README.md
drwxr-xr-x 3 chdorb chdorb    4096 15 oct.  10:45 vendor
