### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by PDVJAM** [shimt/pam-exec-oauth2#2]
We're trying to use this module. But install steps not clear for me...
sudo cp go/bin/pam-exec-oauth2 $PREFIX/pam-exec-oauth2 --- gitrepo doesn't have pam-exec-oauth2.
And if I run build script, I got the following:
root@vagrant:/root/pam-exec-oauth2# ./build-linux-amd64.bat
main.go:31:2: cannot find package "github.com/shimt/go-simplecli" in any of:
	/usr/lib/go-1.10/src/github.com/shimt/go-simplecli (from $GOROOT)
	/home/vagrant/go/src/github.com/shimt/go-simplecli (from $GOPATH)
main.go:32:2: cannot find package "golang.org/x/oauth2" in any of:
	/usr/lib/go-1.10/src/golang.org/x/oauth2 (from $GOROOT)
	/home/vagrant/go/src/golang.org/x/oauth2 (from $GOPATH)

How this module should be installed? Please, help.

**Comment by shimt** [comment]
build-*.bat is script for cross compile.

use 'go build' for native build

root@sample:~# go get github.com/shimt/pam-exec-oauth2
root@sample:~# cd ~/go/src/github.com/shimt/pam-exec-oauth2/
root@sample:~/go/src/github.com/shimt/pam-exec-oauth2# go build
root@sample:~/go/src/github.com/shimt/pam-exec-oauth2# ls -l
total 10932
-rw-r--r-- 1 root root     1072 Nov 11 09:27 LICENSE
-rw-r--r-- 1 root root     1107 Nov 11 09:27 README.md
-rw-r--r-- 1 root root       78 Nov 11 09:27 build-linux-amd64.bat
-rw-r--r-- 1 root root       76 Nov 11 09:27 build-linux-arm.bat
-rw-r--r-- 1 root root       78 Nov 11 09:27 build-linux-arm64.bat
-rw-r--r-- 1 root root     3830 Nov 11 09:27 main.go
-rwxr-xr-x 1 root root 11168965 Nov 11 09:28 pam-exec-oauth2
drwxr-xr-x 1 root root       20 Nov 11 09:27 vendor

**Comment by PDVJAM** [comment]
Ah, right. Thank you!

Have you checked this module with google oauth?

**Comment by shimt** [comment]
No. checked only Azure AD.
Sorry, I not use Google OAuth2 service.
