### ISSUE TITLE
Can't use with Google oAuth

### ISSUE THREAD

**Issue by sassyn** [shimt/pam-exec-oauth2#4]
Hi,

Thanks for the project!
I have manage to make it work with few oAuth provider, but I can't make it work with google.

See here: https://developers.google.com/identity/protocols/oauth2/native-app#uwp

Seems like the token can't be created. 
When doing it manually like in here 
https://gist.github.com/LindaLawton/cff75182aac5fa42930a09f58b63a309

I manage to get a token, but from the module never.
I have try to play with the extra parameters: 
    extra-parameters: {
            code: "4/zQGHtWcSaV_C53wrHLv85xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            grant_type: "authorization_code",

Nothing seems to be working :-(

Can you please help?

    },

**Comment by shimt** [comment]
can't use Google OAuth2 :-(

pam-exec-oauth2 use "Resource Owner Password Credentials Flow".
but, it is unsupported at Google OAuth2.

In addition, I tried on my Google account. 
I was not able to acquire a useful information.

**debugging output (--debug)**
```
2020/05/04 09:58:13 [DEBUG] create oauth2Config
2020/05/04 09:58:13 [DEBUG] ClientID: <cut>
2020/05/04 09:58:13 [DEBUG] ClientSecret: <cut>
2020/05/04 09:58:13 [DEBUG] Scopes: <cut>
2020/05/04 09:58:13 [DEBUG] EndPoint.AuthURL: https://accounts.google.com/o/oauth2/v2/auth
2020/05/04 09:58:13 [DEBUG] EndPoint.TokenURL: https://oauth2.googleapis.com/token
2020/05/04 09:58:13 [DEBUG] create oauth2Context
2020/05/04 09:58:13 [DEBUG] call PasswordCredentialsToken
oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```
